# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JrmAx8cVEzo3mvFZRaKhQhC6ytc1Ov63
"""

print("Hello World") 
a = 5
b = 2
c= a + b
print(c)

print("Площадь треугольника")
a = int(input())
b = int(input())
S = 0,5 * a * b
print (S)

#print ("5 умножение на выбранное число, введите число")
a = 4
b = int(input())
c = a * b
print (c)

print("Возведем в квадрат")
а = int(input())
b = int(input())
c = (a^2+b^2)
print(c)

#Решение неравенства 
print ("Решение неравенства")
a = 3
b = 6
c = 7
x = (a**2 + b**2 - c**3)/2
print(x)

print("Найдем сумму")
a = 15
b = 10
c = 2
x = (a + b)/c
print(c)

print("Решим неравенство")
a = 4
b = 3
x = ((a**3 + 14)/5)*b
print(c)

print("Создадим программу, которая найдет квадрат")
a = int(input())
b = int(input())
n = int(input())
c = ((a**2 + b**2)//n)
print(c)

print("Выведем результат")
a = int(input())
b = int(input())
c = (a // b)
x = (a * b)
n = (a % b)
print (c)
print (x)
print (n)

print("Повышенная сложность")
sek = int(input())
min = sek / 60
hour = sek / 3600 
day = sek / 86400
print(sek, hour, day)

print("Число n")
n = int(input())
n = n + (n*n) + (n*n*n)
print("Результат: ", n)