# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rrcghsvQvejPT-evw6ljDW7aMeVhUg8
"""



#print("Задание 1")
months = ["Янаварь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", " Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"]
number = int(input("Введите номер вашего месяца "))
if number > 0 and number < 13:
  print("Ваш  месяц это ", str(months[number - 1]))
else:
  print("Введите, пожалуйста, НОРМАЛЬНЫЙ номер")

#print("Задание 2")
x = int(input("Введите ваше число "))
if x % 2 == 0: 
  print("Ваше число четное")
else:
  print("Ваше число нечетное")

#print("Задание 3")
n = int(input("Введите число "))
if n > 40: 
  print("Stonks")
else:
  print("Not stonks")

#print("Задание 4")
def is_year_leap(year):
  if year % 4 == 0 and year % 400 == 0 and year % 100 != 0:
    print("Ваш год является високосным")
  else:
    print("Ваш год не является високосным")
a = int(input("Введите год "))
is_year_leap(a)

print("Задание 5")
def is_prime(number):
for i in range(number):
  if number % (i + 1) == 0
   return True
  else:
   return True
a = int(input('Ввежите число '))

is_prime(a)

#print("Задание 6")
c = (-138/2)**1.3
a = int(input("Введите заначение первой переменной "))
b = int(input("Введите заначение второй переменной "))
if a / b == 3.6:
   a, b = b, a
elif b <= abs(c) and b >= (-69 / 28 ** 5.1)*4:
   a, b = b, a
print(a, b)

#print("Задание 7")
digits = []
for i  in range (5):
  print("Введите число № " , str(i + 1))
  x = int(input())
  digits.append(x)
DigitsArray = set(digits)
if len(DigitsArray) == len(digits):
  print("Все числа уникальны")
else: 
  print("В списке есть повторения")
even_numbers = 0
for i in range(len(digits)):
  if digits[i] % 2 == 0:
    even_numbers += 1
  else:
    pass
print("Всего четных чисел: ", str(even_numbers))    
NegativeNumbers = 0
for i in range(len(digits)):
  if digits[i] < 0:
    NegativeNumbers += 1
print("Всего отрцательных чисел: ", str(NegativeNumbers))
SpecifiedNumbers = 0
for i in range(len(digits)):
  if digits[i] >= -256 or digits[i] >= 1024:
    SpecifiedNumbers += 1
print("Всего чисел в  промежутке [-256 ; 1024]: ", str(SpecifiedNumbers))1